name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Debug Private Key
      run: echo "${{ secrets.PRIVATE }}"
    - name: Setup SSH and Deploy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 134.122.97.43
        username: root
        key: ${{ secrets.PRIVATE }}
        passphrase: elvit
        port: 22
        script: |
          cd elvit.backend
    
