name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH and Deploy
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: 134.209.18.189
        username: root
        key: |
            ${{ secrets.PRIVATE }}
            elvit
        port: 22
        script: |
          cd elvit.backend
    
